import React, { useState, useEffect, useMemo, useCallback } from "react";
import { useNavigate } from "react-router-dom";
import "./transactionHistory.css";
import Sidebar from "../shared/sidebar";
import Header from "../shared/header";
import CustomDateModal from "../shared/customDateModal";
import DataTable from "react-data-table-component";
import TransHisModal from "./modals/transactionDetailsModal";
import jsPDF from "jspdf";
import "jspdf-autotable";
import logo from "../../../assets/logo.png";
import {
  startOfToday,
  startOfWeek,
  startOfMonth,
  startOfYear,
  endOfToday,
  endOfWeek,
  endOfMonth,
  endOfYear,
} from "date-fns";

const getAuthToken = () => localStorage.getItem("authToken");
const API_URL = "http://127.0.0.1:9000/auth/purchase_orders/all";
const transformApiData = (apiTransaction) => {
  const subtotal = apiTransaction.orderItems.reduce(
    (acc, item) => acc + item.price * item.quantity, 0);
const discount = subtotal - apiTransaction.total;

  return {
    id: apiTransaction.id,
    date: new Date(apiTransaction.date).toISOString(),
    orderType: apiTransaction.orderType,
    items: apiTransaction.orderItems.map((item) => ({
      name: item.name,
      quantity: item.quantity,
      price: item.price,
      details:
        item.addons && Object.values(item.addons).some((v) => v > 0)
          ? "Includes add-ons"
          : undefined,
    })),
    total: apiTransaction.total,
    subtotal: subtotal,
    discount: discount,
    status:
      apiTransaction.status.charAt(0).toUpperCase() +
      apiTransaction.status.slice(1),
    paymentMethod: apiTransaction.paymentMethod,
    type: "Store",
    discountsAndPromotions: discount > 0 ? "Discount Applied" : "None",
    cashierName: apiTransaction.cashierName,
    GCashReferenceNumber: apiTransaction.GCashReferenceNumber,
  };
};

function TransactionHistory() {
  const navigate = useNavigate();

  const [activeTab, setActiveTab] = useState("Store");
  const [transactions, setTransactions] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);
  const [selectedTransaction, setSelectedTransaction] = useState(null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [dateRange, setDateRange] = useState("thisWeek");
  const [isCustomModalOpen, setIsCustomModalOpen] = useState(false);
  const [customStart, setCustomStart] = useState("");
  const [customEnd, setCustomEnd] = useState("");
  const fetchTransactions = useCallback(async (token) => {
    setIsLoading(true);
    setError(null);
    try {
      const response = await fetch(API_URL, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });
      if (!response.ok) {
        throw new Error(`HTTP error! Status: ${response.status}`);
      }

      const data = await response.json();
      const transformedData = data.map(transformApiData);
      setTransactions(transformedData);
    } catch (err) {
      console.error("Failed to fetch transactions:", err);
      setError(
        "Failed to load transaction data. Please check the connection and try again."
      );
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    const token = getAuthToken();
    if (!token) {
      navigate("/");
      return;
    }
    fetchTransactions(token);
  }, [navigate, fetchTransactions]);

  const handleClearFilters = () => {
    setSearchTerm("");
    setStatusFilter("");
    setDateRange("today");
    setCustomStart("");
    setCustomEnd("");
  };

 
  const handleExport = () => {
    const doc = new jsPDF();
    doc.addImage(logo, "PNG", 150, 10, 40, 30);
    doc.setFontSize(14);
    doc.text(`Transaction History - ${activeTab}`, 14, 20);
    doc.setFontSize(10);
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, 28);
    doc.text("Transaction Date Range: All Dates", 14, 34);
    doc.text(`Status: ${statusFilter || "All"}`, 14, 40);
    doc.text("Generated by: Admin", 14, 45);
   
    doc.autoTable({
      startY: 50,
      head: [
        [
          "Transaction ID",
          "Date",
          "Cashier",
          "Order Type",
          "Item(s)",
          "Discounts",
          "Total",
          "Payment Method",
          "Status",
        ],
      ],
      body: transactions.map((t) => [
        t.id,
        new Date(t.date).toLocaleDateString(),
        t.cashierName || "—",
        t.orderType || "—",
        t.items?.length || 0,
        t.discountsAndPromotions || "None",
        `₱${parseFloat(t.total).toFixed(2)}`,
        t.paymentMethod || "N/A",
        t.status,
      ]),
      theme: "grid",
      headStyles: { fillColor: [75, 146, 157], textColor: 255 },
      styles: { fontSize: 9 },
    });

    const totalSales = transactions.reduce(
      (sum, t) => sum + parseFloat(t.total),
      0
    );
    const totalItems = transactions.reduce(
      (sum, t) => sum + (t.items?.length || 0),
      0
    );
    const discountsApplied = transactions.filter((t) => t.discount > 0).length;
    let finalY = doc.lastAutoTable.finalY + 10;
    doc.setFontSize(12);
    doc.text("Transaction History Summary", 14, finalY);
    doc.setFontSize(10);
    doc.text(`Total Transactions: ${transactions.length}`, 14, finalY + 8);
    doc.text(`Total Sales: ₱${totalSales.toFixed(2)}`, 14, finalY + 16);
    doc.text(`Total Items: ${totalItems}`, 14, finalY + 24);
    doc.text(`Total Discount Applied: ${discountsApplied}`, 14, finalY + 32);
    doc.text("Promotion Applied: 0", 14, finalY + 40);
    doc.save("Transaction_History.pdf");
  };

  const getDateRange = () => {
    const now = new Date();
    switch (dateRange) {
      case "today":
        return [startOfToday(), endOfToday()];
      case "thisWeek":
        return [startOfWeek(now, { weekStartsOn: 1 }), endOfWeek(now, { weekStartsOn: 1 })];
      case "thisMonth":
        return [startOfMonth(now), endOfMonth(now)];
      case "thisYear":
        return [startOfYear(now), endOfYear(now)];
      case "custom":
        return customStart && customEnd
          ? [new Date(customStart), new Date(customEnd)]
          : [null, null];
      default:
        return [null, null];
    }
  };

  const filteredTransactions = useMemo(() => {
    const [start, end] = getDateRange();
    return transactions.filter((transaction) => {
      const matchesTab = activeTab === "Store";
      const matchesSearch = (transaction.id || "")
        .toString()
        .toLowerCase()
        .includes(searchTerm.toLowerCase());
      const matchesStatus =
        statusFilter === "" || transaction.status === statusFilter;
      const tDate = new Date(transaction.date);
      const matchesDate = !start || !end || (tDate >= start && tDate <= end);
      return matchesTab && matchesSearch && matchesStatus && matchesDate;
    });
  }, [activeTab, transactions, searchTerm, statusFilter, dateRange, customStart, customEnd]);

  useEffect(() => {
    setStatusFilter("");
    setSearchTerm("");
  }, [activeTab]);

  const uniqueStatuses = useMemo(() => {
    return [...new Set(transactions.map((item) => item.status).filter(Boolean))];
  }, [transactions]);

  const handleRowClick = (row) => {
    setSelectedTransaction(row);
    setIsModalOpen(true);
  };
  const closeModal = () => {
    setIsModalOpen(false);
    setSelectedTransaction(null);
  };

  const columns = [
    { name: "TRANSACTION #", selector: (row) => row.id, sortable: true, width: "14%" },
    { name: "DATE", selector: (row) => new Date(row.date).toLocaleDateString(), sortable: true, width: "8%" },
    { name: "CASHIER", selector: (row) => row.cashierName || "—", width: "12%" },
    { name: "ORDER TYPE", selector: (row) => row.orderType || "—", width: "10%" },
    { name: "ITEM(S)", selector: (row) => row.items?.length || 0, center: true, sortable: true, center: true,  width: "9%" },
    { name: "DISCOUNTS", selector: (row) => row.discountsAndPromotions || "—", width: "11%" },
    { name: "TOTAL", selector: (row) => `₱${parseFloat(row.total).toFixed(2)}`, center: true, sortable: true, width: "12%" },
    { name: "PAYMENT METHOD", selector: (row) => row.paymentMethod || "N/A", center: true, width: "13%" },
    {
      name: "STATUS",
      selector: (row) => row.status,
      cell: (row) => <span className={`status-badge ${row.status.toLowerCase()}`}>{row.status}</span>,
      center: true,
      sortable: true,
      width: "11%",
    },
  ];

  return (
    <div className="transaction-history">
      <Sidebar />
      <div className="transHis">
        <Header pageTitle="Transaction History" />
        <div className="transHis-content">
          <div className="tabs">
            <button className={`tab ${activeTab === "Store" ? "active-tab" : ""}`} onClick={() => setActiveTab("Store")}>Store</button>
            <button className={`tab ${activeTab === "Online" ? "active-tab" : ""}`} onClick={() => setActiveTab("Online")}>Online</button>
          </div>

          <div className="transHis-filter-bar">
              <input type="text" placeholder="Search by Transaction Number..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} />
              <select value={dateRange} onChange={(e) => { const v = e.target.value; setDateRange(v); if (v === "custom") setIsCustomModalOpen(true); }}>
                <option value="today">Today</option>
                <option value="thisWeek">This Week</option>
                <option value="thisMonth">This Month</option>
                <option value="thisYear">This Year</option>
                <option value="custom">Custom</option>
              </select>
              <select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}>
                <option value="">Status: All</option>
                {uniqueStatuses.map((s) => <option key={s} value={s}>{s}</option>)}
            </select>
            <button className="history-clear-btn" onClick={handleClearFilters}>Clear Filters</button>
            <button className="history-export-btn" onClick={handleExport}>Export</button>
          </div>

          <div className="transactions-table-container">
            <DataTable
              columns={columns}
              data={filteredTransactions}
              striped
              highlightOnHover
              responsive
              pagination
              fixedHeader
              fixedHeaderScrollHeight="60vh"
              onRowClicked={handleRowClick}
              pointerOnHover
              noDataComponent={<div style={{ padding: "24px" }}>No transactions found.</div>}
              customStyles={{
                headCells: {
                  style: {
                    backgroundColor: "#4B929D",
                    color: "#fff",
                    fontWeight: "600",
                    fontSize: "14px",
                    padding: "12px",
                    textTransform: "uppercase",
                    textAlign: "center",
                    letterSpacing: "1px",
                  },
                },
                rows: {
                  style: {
                    minHeight: "55px",
                    padding: "5px",
                  },
                },
              }}
            />
            <TransHisModal show={isModalOpen} onClose={closeModal} transaction={selectedTransaction} />
          </div>
          <CustomDateModal show={isCustomModalOpen} onClose={() => setIsCustomModalOpen(false)} onApply={(s, e) => { setCustomStart(s); setCustomEnd(e); }} />
        </div>
        
      </div>
    </div>
  );
}

export default TransactionHistory;
