import logo from "../../../assets/logo.png";
import "./salesReportExport.css";

const handleSalesReportExport = (reportData, reportTotals, activeTab, currentPeriodText, exportedBy = "System") => {
  const modal = document.createElement("div");
  modal.className = "export-modal";

  modal.innerHTML = `
    <div class="export-modal-content">
      <h2>Choose Export Format</h2>
      <p>Choose which type of file to export.</p>
      <button id="exportPDF" class="sales-export-btn pdf">Export as PDF</button>
      <button id="exportCSV" class="sales-export-btn csv">Export as CSV</button>
      <button id="cancelExport" class="sales-export-btn cancel">Cancel</button>
    </div>
  `;

  document.body.appendChild(modal);
  document.getElementById("cancelExport").onclick = () => modal.remove();
  document.getElementById("exportPDF").onclick = () => {
    modal.remove();
    if (!reportData.length) {
      const noDataModal = document.createElement("div");
      noDataModal.className = "no-data-modal";
      noDataModal.innerHTML = `
        <div class="no-data-content">
          <h2>No Sales Data</h2>
          <p>There is no sales data available to export.</p>
          <button id="closeNoData">Okay</button>
        </div>
      `;
      document.body.appendChild(noDataModal);
      document.getElementById("closeNoData").onclick = () => noDataModal.remove();
      return;
    }

    const newWindow = window.open("", "_blank");
    newWindow.document.write(`
      <html>
        <head>
          <title>Sales Report Export</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 20px; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
            h1 { margin: 0; font-size: 18px; }
            .export-header { display: flex; align-items: flex-start; margin-bottom: 15px; }
            .export-header img { height: 110px; }
            .header-details { text-align: left; font-size: 13px; margin-left: 15px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { border: 1px solid #000; padding: 8px; font-size: 11px; text-align: center; }
            th { background-color: #4B929D !important; color: #fff !important; font-weight: bold; }
            .summary { margin-top: 30px; font-size: 12px; text-align: center; }
            .summary-table { border-collapse: collapse; width: 60%; margin: 0 auto; }
            .summary-table th, .summary-table td { border: 1px solid #000; padding: 8px; font-size: 12px; text-align: left; }
            .summary-table th { background: #f2f2f2; width: 50%; }
            .approved { margin-top: 40px; text-align: right; }
            .signature { margin-top: 40px; }
          </style>
        </head>
        <body>
          <div class="export-header">
            <img src="${logo}" alt="Logo" />
            <div class="header-details">
              <h1>Sales Report - ${activeTab}</h1>
              <p><strong>Generated On:</strong> ${new Date().toLocaleString()}</p>
              <p><strong>Generated By:</strong> ${exportedBy}</p>
              <p><strong>Period:</strong> ${currentPeriodText}</p>
            </div>
          </div>

          <table>
            <thead>
              <tr>
                ${Object.keys(reportData[0]).map(key => `<th>${key.toUpperCase()}</th>`).join("")}
              </tr>
            </thead>
            <tbody>
              ${reportData.map(row => `
                <tr>
                  ${Object.values(row).map(val => `<td>${val}</td>`).join("")}
                </tr>
              `).join("")}
            </tbody>
          </table>

          <div class="summary">
            <h3>Sales Summary</h3>
            <table class="summary-table">
              <tr><th>Total Transactions</th><td>${reportTotals.transactions}</td></tr>
              <tr><th>Items Sold</th><td>${reportTotals.itemsSold}</td></tr>
              <tr><th>Store Sale</th><td>₱${reportTotals.storeSale.toFixed(2)}</td></tr>
              <tr><th>Online Sale</th><td>₱${reportTotals.onlineSale.toFixed(2)}</td></tr>
              <tr><th>Total Sale</th><td>₱${reportTotals.totalSale.toFixed(2)}</td></tr>
            </table>
          </div>

          <div class="approved">
            <p>Approved By:</p>
            <div class="signature">________________________</div>
          </div>

          <script> window.onload = () => window.print(); </script>
        </body>
      </html>
    `);
    newWindow.document.close();
  };

  // CSV Export
  document.getElementById("exportCSV").onclick = () => {
    modal.remove();

    if (!reportData.length) {
      alert("No sales data to export");
      return;
    }

    const headers = Object.keys(reportData[0]);
    const rows = reportData.map(obj => headers.map(h => obj[h]));

    const csvContent = [headers, ...rows].map(e => e.join(",")).join("\n");
    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute("download", `sales_report_${Date.now()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };
};

export default handleSalesReportExport;
